# Generated by Django 4.2.5 on 2023-09-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_mat', models.CharField(max_length=40, verbose_name='Материалы затраты')),
                ('sum_uslug', models.CharField(max_length=40, verbose_name='Цена услуг')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnoz', models.CharField(max_length=40, verbose_name='Диагноз')),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Кличка пациента')),
                ('adres', models.CharField(max_length=40, verbose_name='Адрес')),
                ('tel', models.CharField(max_length=40, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя доктора')),
                ('spec', models.CharField(max_length=40, verbose_name='Специальность доктора')),
            ],
        ),
        migrations.CreateModel(
            name='Zapisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=40, verbose_name='Номер записи')),
                ('num_vizit', models.CharField(max_length=40, verbose_name='Номер визита')),
                ('data_vizit', models.DateField(null=True, verbose_name='Дата визита')),
                ('anamnez', models.CharField(max_length=40, verbose_name='Анамнез')),
                ('shema_lechenia', models.TextField(max_length=500, verbose_name='Схема лечения')),
                ('chek_uslug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.check')),
                ('diagnoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.diagnoz')),
                ('pacient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.pacient')),
                ('spec', models.ManyToManyField(to='catalog.spec')),
            ],
        ),
    ]
